import './Experience.css';

function Experience() {
  return (
    <div className="Experience">
      <div className="exp-card">
        <h1> Outlier </h1>
        <h2> AI Trainer </h2>
        <div> - Engineer coding prompts designed to fail Large Language Models (LLMs), and evaluate and rewrite model-generated responses to enhance model performance based on project criteria </div>
        <div> - Debug and edit code snippets in Java and Python generated by LLMs to improve accuracy and relevance </div>
        <div> - Review tasks completed by other contributors, providing helpful feedback and edits to ensure quality </div>
      </div>
      <div className="exp-card">
        <h1> Revvity </h1>
        <h2> Software Engineer Intern </h2>
        <div> - Developed a machine learning model to classify mouse poses (laying on back, stomach, side) in a given image for health condition detection with 90+% accuracy using PyTorch and AlexNet CNN architecture </div>
        <div> - Trained existing machine learning model used for health condition detection in mice by tagging and labeling mice anatomy on 200+ images using Computer Vision Annotation Tool (CVAT) </div>
        <div> - Mapped coordinates of input fields on dry blood spot cards used for newborn screening using React and GIMP </div>
      </div>
    </div>
  );
}

export default Experience;
